### ISSUE TITLE
sematic data structure

### ISSUE THREAD

**Issue by cfhaak** [bundesverfassung-oesterreich/bv-transkribus-export-play#8]
https://github.com/bundesverfassung-oesterreich/bv-transkribus-export-play/blob/4a241512932766ab7bb0226bfab151c25444ad25/editions/bv-doc-id-3.xml#L591

structure-levels between articles and top-level sections are extremely hard to find, they seem to change too from document to document.

**Comment by csae8092** [comment]
let's only process articles into dedicated `tei:div` elements, bigger groups as Abschnitte and Unterabschnitte can be curated manually quite easy and fast
